### ISSUE TITLE
When closing a comic, Simple Comic shows the error "The file doesn't exist" twice

### ISSUE THREAD

**Issue by NandoSD** [MaddTheSane/Simple-Comic#102]
This error appears TWICE every time I close a comic. The error popup has "OK" button to click to close the popup. 

Simple Comic Version 1.9.7 (348)
Macbook Pro M1
Ventura 13.3.1 (22E261)

**Comment by nickv2002** [comment]
Thanks for the bug report. I haven't seen this behavior before. Can you give us any other info to help us figure out what is happening?

- Does it happen with other versions of Simple Comic? (See [Releases](https://github.com/MaddTheSane/Simple-Comic/releases) to download earlier versions)
- Can you use Console.app to start a recording, filter it down to `SimpleComic`, and then duplicate the issue? Sharing those logs could help.

**Comment by NandoSD** [comment]
Nick—

The odd behavior stopped after I restarted the computer. If I see it again I will try what you suggested with Console (which I have never used) and an older version of the app.

—Nando

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by nickv2002** [comment]
closing for now, can reopen if it happens again
