### ISSUE TITLE
Cannot change full screen background color. 

### ISSUE THREAD

**Issue by ghost** [MaddTheSane/Simple-Comic#103]
On version 1.9.7 full screen background color is not able to be modified in the settings there seems to be a bug.

When I download 1.9.6 this issue was not there.

Attmped remedies:
- Delete and reinstall app
- Format Macbook and reinstall

Environment:
Simple Comic 1.9.7
MacBook Air M2
MacOS 13.3.1

**Comment by Boognoss** [comment]
Same issue for me on similar hardware.

Simple Comic 1.9.7
Mac mini M1 / Mac mini M2
Both systems running MacOS 13.4

Regardless of what colour is selected, it stays white when in full screen.

**Comment by waaykool** [comment]
Same here. 
Simple Comic 1.9.7
iMac Intel, Ventura 13.3.1

Only white background in full screen.

Edit: This feature works as expected using Simple Comic 1.9.6

Edit#2: I am able to set a new background color within settings using Simple Comic vers 1.9.6. If I then quit 1.9.6, and re-open 1.9.7, Simple Comics 1.9.7 will display background color as previously set in 1.9.6 - but will then not be able to change _that_ color from within 1.9.7. (So if I set a black background in 1.9.6, then 1.9.7 will open with a black background that can't be changed within 1.9.7).

**Comment by MaddTheSane** [comment]
My guess is I went into a modernize phase and didn't use the correct decoder function, so I just reverted it to use the older behavior.

The next release should fix this issue.

**Comment by nickv2002** [comment]
BTW, I'll plan to update this soon. Haven't pushed an update yet because there were some [Xcode issues](https://github.com/apple/swift/issues/68163) this fall that I didn't have time to work around.

**Comment by nickv2002** [comment]
I think this is fixed in the https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise

**Comment by waaykool** [comment]
Yes! This does work as expected now. Thanks for keeping me in mind!

     On Sunday, December 31, 2023 at 10:47:00 AM PST, Nick Vance ***@***.***> wrote:  
 
 


I think this is fixed in https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise
