### ISSUE TITLE
Feature request: Text to speech

### ISSUE THREAD

**Issue by Cypher69er** [MaddTheSane/Simple-Comic#104]
I saw this tweet and was wondering how hard it would be to make Simple Comic's OCR accessible to Apple's text-to-speech?

https://twitter.com/jhoetzl/status/1669151135733522434

**Comment by nickv2002** [comment]
You can already select text in a comic and have MacOS speak it (see https://github.com/MaddTheSane/Simple-Comic#live-text-support). I'm not an expert on what other accessibility features would be helpful here. Please elaborate on specifics.

**Comment by Cypher69er** [comment]
Thanks Nick, couldn’t get it working but didn’t realise it was Apple Silicon only.

Will have a play with "select all" etc.
