### ISSUE TITLE
background color is always white

### ISSUE THREAD

**Issue by unstoppablecarl** [MaddTheSane/Simple-Comic#105]
The background color is always white no matter what color I set it to. 

Simple Comic Version 1.9.7 (348)
MacOs Ventura 13.2.1

**Comment by nickv2002** [comment]
Thanks for the report. This is a duplicate of https://github.com/MaddTheSane/Simple-Comic/issues/103
Will be fixed in next release.

**Comment by nickv2002** [comment]
I think this is fixed in https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.8

LMK if otherwise in https://github.com/MaddTheSane/Simple-Comic/issues/103
