### ISSUE TITLE
Background colour in Fullscreen not working.

### ISSUE THREAD

**Issue by ChiefGit00** [MaddTheSane/Simple-Comic#108]
The background colour in Fullscreen is always white. Not respecting choice.

PS: The most excellent app for comic reading. All features are already perfect. Thanks for your efforts.
![Screenshot 2023-12-12 at 1 52 37 AM](https://github.com/MaddTheSane/Simple-Comic/assets/45871308/afd3292c-17de-4b45-a85d-daf381fa88cf)
![Screenshot 2023-12-12 at 1 52 44 AM](https://github.com/MaddTheSane/Simple-Comic/assets/45871308/b5a3ffb9-57cc-4908-8acc-9c0c8312effe)

**Comment by nickv2002** [comment]
Thanks for the report, known problem see https://github.com/MaddTheSane/Simple-Comic/issues/103#issuecomment-1850853327
