### ISSUE TITLE
Modify date - Question

### ISSUE THREAD

**Issue by abillauer** [MaddTheSane/Simple-Comic#116]
Hi,

When I open comic files with simple comic it often changes the file modify date of the comic file. Is there a way to ensure simple comic doesn't change the files it is reading? 

Thanks!

**Comment by nickv2002** [comment]
I tested 5 different CBZ and CBR files and couldn't dupe this behavior with v1.9.8
Can you provide more details, examples, and version numbers to help us track this down?

**Comment by abillauer** [comment]
Hi, I am opening a cbz on a SMB share on a diskstation NAS. The share has read/write permissions. 

You can see the before here:
 
<img width="682" alt="Screenshot 2024-04-28 at 1 33 48 PM" src="https://github.com/MaddTheSane/Simple-Comic/assets/73428493/df1bfd83-8440-4669-b64e-efd34c485734">


and the after here:

<img width="692" alt="Screenshot 2024-04-28 at 1 34 31 PM" src="https://github.com/MaddTheSane/Simple-Comic/assets/73428493/47274e2e-cd34-44d1-aa9a-4a81b798c3bc">


What is interesting is that the MD5 sum of the file stays the same.  I am not sure if this is a real issue or a mac/UI issue or if I am just reading this wrong.

**Comment by DavidPhillipOster** [comment]
That _the MD5 sum of the file stays the same_ is a clue.  If it were on a mac native file system, I'd ask you to do, on the command-line, an  `ls -l@` on that file, to see what kind of metadata is being stored for it.  And, Command-click on the header column of the table to get a list of possible columns and enable the **Date Last Opened** column. It is possible that SMB accessed from macOS gets it wrong, and modifies _last modified_ whenever it modifies the _last opened_ value.

**Comment by abillauer** [comment]
It seems to be exactly that. 

```
 ls -l@ The\ Peacemaker\ \#001\ \(1967\).cbz 
-rwx------@ 1 XXX  staff  51213225 Apr 28 13:37 The Peacemaker #001 (1967).cbz
	com.apple.lastuseddate#PS	      16 
	com.apple.quarantine	      30
``` 


When I copy the file locally and add all the columns the date last open updates but not the date modified. 

<img width="795" alt="Screenshot 2024-04-28 at 6 36 15 PM" src="https://github.com/MaddTheSane/Simple-Comic/assets/73428493/a23e2f07-cdaa-42ed-83bb-88fe25862668">

**Comment by nickv2002** [comment]
Closing as this is outside of Simple Comic's control/correct behavior.

**Comment by abillauer** [comment]
Thanks for all of your help! I really appreciate it!!!
