### ISSUE TITLE
Switch full screen shortcut to Command-F

### ISSUE THREAD

**Issue by plgagne** [MaddTheSane/Simple-Comic#119]
Simple Comic is a reader app. It should therefore use the Command-F shortcut to switch to full screen, like other apps meant to consume content, like Quicktime or TV. The Command-F shortcut is currently used by Find ... which is far less useful for an app meant to read first and foremost, with its robust search capabilities allowing a user to search within files coming in second.

**Comment by nickv2002** [comment]
Thanks for the feedback. We match the default shortcuts for Preview.app which I think is Simple Comic's closest cousin on macOS. This means:

- Command-F for Find
- Globe-F for Full Screen

(Incidentally these are also the keyboard shortcuts used for Safari)

I understand if that might not match everyone's prefs. If they doesn't match yours it's very easy to [remap them with tools built into macOS](https://support.apple.com/guide/mac-help/create-keyboard-shortcuts-for-apps-mchlp2271/mac).
