### ISSUE TITLE
Changes for App Store Submission

### ISSUE THREAD

**Issue by nickv2002** [MaddTheSane/Simple-Comic#12]
We should make some changes for App Store submission.

1. I already updated the Readme with a privacy policy https://github.com/MaddTheSane/Simple-Comic/commit/cfade4a4688004a3adc3501dc466e1e454729ac6
1. Please remove the link to Dancing Tortoise in the title. We can link to app store or elsewhere later. <img width="1031" alt="Screen Shot 2020-02-01 at 3 30 25 PM" src="https://user-images.githubusercontent.com/704392/73600657-641e8c80-4508-11ea-800b-1cf70a6ef401.png">
1. I plan to use the newest commit unless there are any known issues: https://github.com/MaddTheSane/Simple-Comic/commit/0980fa0eef179d5070f079c7255a319536994166

**Comment by MaddTheSane** [comment]
Link removed.

**Comment by nickv2002** [comment]
Simple Comic is now up on the [Mac App Store](https://apps.apple.com/us/app/simple-comic/id1497435571?ls=1&mt=12) Give it a try and let me know if you see any issues.

It's based on this build https://github.com/MaddTheSane/Simple-Comic/commit/ea03edc9a5e33305190e1013b95b796c3392d69c so there may be a few commits after this. I'll push a new build at some point if everything else looks OK with the one there now. LMK
