### ISSUE TITLE
Support for Quick Look Generator plugins is being removed on macos 15 sequoia

### ISSUE THREAD

**Issue by devmatcha** [MaddTheSane/Simple-Comic#121]
Per the macos release [notes](https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes#:~:text=Support%20for%20deprecated%20Quick%20Look%20Generator%20plugins%20is%20being%20removed.%20To%20provide%20previews%20and%20thumbnails%20for%20your%20custom%20file%20types%2C%20migrate%20to%20Quick%20Look%20Preview%20Extension%20and%20Thumbnail%20Extension%20API.%20(116791365)) 

>Support for deprecated Quick Look Generator plugins is being removed. To provide previews and thumbnails for your custom file types, migrate to Quick Look Preview Extension and Thumbnail Extension API. (116791365)

Hopefully this can be fixed with the release of sequoia

**Comment by MaddTheSane** [comment]
There's already a Quick Look Preview Extension and a Thumbnail Extension in the code, as well as the Quick Look generator plug-in.
