### ISSUE TITLE
Qucklook Plugin in Mac OS Sequoia didn't work

### ISSUE THREAD

**Issue by msaggion** [MaddTheSane/Simple-Comic#124]
When I updated to Sequoia, Quicklook preview and thus builder stop working, any ideas?

**Comment by MaddTheSane** [comment]
You might need to enable the Quick Look extension in System Settings.

**Comment by msaggion** [comment]
Thanks for fast response

It's here? If so, this was already enabled

<img width="567" alt="Screenshot 2024-10-18 at 6 25 31 PM" src="https://github.com/user-attachments/assets/2f32f560-ff0a-49f6-9304-220aea0a5963">

**Comment by msaggion** [comment]
I uninstall all rar/zip related apps (including Simple Comic) install SC again and it works, thanks!
