### ISSUE TITLE
'ghost' cbr's showing when Ctl-clicking on app icon in doc

### ISSUE THREAD

**Issue by FediMakasu** [MaddTheSane/Simple-Comic#128]
General setting for not showing recent files is working in Simple Comic just fine, but am seeing a list of older cbr's when right clicking on the doc icon, which also show as icons when 'show all windows' option is selected (though these files are not accessible).   Can't figure out how to remove these and if they are cached somewhere.

**Comment by nickv2002** [comment]
I think these will clear from File -> Open Recent -> Clear Menu
![Screenshot 2024-11-27 at 11 12 28 AM](https://github.com/user-attachments/assets/29a8e61e-be02-4fca-98db-8c367bda4f6b)

**Comment by FediMakasu** [comment]
it's a good thought unfortunately that was already greyed out with these ghost cbr's still showing. Right-clicking on the dock icon still lists a number of titles above the Options there.  This is what made me thought it was a different issue to items being stuck as 'recently viewed'

**Comment by nickv2002** [comment]
Hmm, I need to test more as it seemed to work for me. I'll report back in a few days.

**Comment by DavidPhillipOster** [comment]
I've seen something like this when I've restarted my Mac, with Simple Comic open at the previous shutdown, and the open .cbz is on an external "spinning platter" USB drive. On restart, the system starts Simple Comic, but the disk hasn't yet spun up and become mounted, so Simple Comic shows its error dialog box.  There really isn't a good fix for Simple Comic since it doesn't have a crystal ball to predict the future - the previous disk might, or might not, appear. So, the spurious error dialog is just a minor inconvenience I live with.

**Comment by DavidPhillipOster** [comment]
Reading the bug report more closely: 
![Screenshot 2024-11-27 at 1 32 01 PM](https://github.com/user-attachments/assets/fd83e224-53ee-4222-b47f-6555fe92daf9)
ghost entries in the dock menu is an Apple Finder bug: all apps do that. I see it, for example, Text Edit continues to show files in the Dock that I've long deleted and don't show in Text Edit's Recent Files menu.

**Comment by FediMakasu** [comment]
I should add - that deleting (eg using an app like AppCleaner to remove the plists etc) and re-installing keeps this ghost list of previously opened files on top of the icon too, which is what is making me think the link is somewhere on my computer

**Comment by FediMakasu** [comment]
@DavidPhillipOster ugh, ok.  that could explain it!

**Comment by DavidPhillipOster** [comment]
If you, in Terminal:

    open ~/Library/Application\ Support/com.apple.sharedfilelist

and sort by date, you'll see some of the files the the system uses to build these menus.

**Comment by FediMakasu** [comment]
@DavidPhillipOster I have found a solution/workaround.  It's not elegant but I was able to clear the list of ghost cbr's from showing the Simple Comic dock icon, but re-enabling 'show recent files' within macOS general settings, opening a new cbr (which showed correctly in the recent file list), again disable recent files from showing and it cleared the Simple Comic list.   to your point, this is a macOS/Finder issue rather than Simple Comic (which stays great, hurrah!)
