### ISSUE TITLE
it's a good thought unfortunately that was already greyed out with these ghost cbr's still showing. Right-clicking on the dock icon still lists a number of titles above the Options there.  This is what made me thought it was a different issue to items being stuck as 'recently viewed'

### ISSUE THREAD

**Issue by FediMakasu** [MaddTheSane/Simple-Comic#129]
it's a good thought unfortunately that was already greyed out with these ghost cbr's still showing. Right-clicking on the dock icon still lists a number of titles above the Options there.  This is what made me thought it was a different issue to items being stuck as 'recently viewed'

_Originally posted by @FediMakasu in https://github.com/MaddTheSane/Simple-Comic/issues/128#issuecomment-2504628417_

**Comment by nickv2002** [comment]
Comment for for #128
