### ISSUE TITLE
AppStore version 1.8.4 can't open cbr/cbz files

### ISSUE THREAD

**Issue by roosterboy** [MaddTheSane/Simple-Comic#16]
I just installed version 1.8.4 from the AppStore and it won't open any of my CB[RZ] files. I can't set Simple Comic as the default app for those file types in the Finder's Get Info window, it doesn't come up as an option when I right-click and select Open With... in Finder, and file names are grayed out and unselectable when I try using the application's Open menu.

I restarted my laptop and also went into System Preferences to grant Full Disk Access to Simple Comic. I deleted and re-installed the application. None of it helped.

At a loss here.

(This is on macOS 10.15.3, if that makes a difference.)

**Comment by MaddTheSane** [comment]
Run an `mdls` on a cbr/cbz file.
I can only think that something else is taking over the cbr/cbz files' UTI for itself.

**Comment by roosterboy** [comment]
The kMDItemContentType attribute was set to 'com.yacreader.yacreader.cbz'. I uninstalled YACReader and now Simple Comic can open my files and I get the QuickLook back. Man, how I missed that!

Thanks!
