### ISSUE TITLE
Can't skip to first page

### ISSUE THREAD

**Issue by perogiue** [MaddTheSane/Simple-Comic#23]
Just a minor issue I noticed.

You can't skip to page 1 if you're on page 2-9.

If you're on page 10, skip towards page one, then page left/right away from the first page, the app jumps to the first page.

If you're on page 10, skip towards page one, then page left/right towards the first page, the app jumps to the last page.

This was seen on 1.8.4 (App Store version) and wasn't seen in 1.7.1.

**Comment by MaddTheSane** [comment]
What OS are you using?

**Comment by perogiue** [comment]
Mojave 10.14.6 (18G2022)
