### ISSUE TITLE
Support HEIF/HEIC

### ISSUE THREAD

**Issue by nickv2002** [MaddTheSane/Simple-Comic#27]
Request from https://github.com/MaddTheSane/Simple-Comic/issues/3#issuecomment-644773804
(HEIF is the format, HEIC is the container)

Mac OS supports these natively, so it would be a matter of detecting the format and connecting to the right supporting libs.

**Comment by MaddTheSane** [comment]
If `NSImage` supports it, it should automatically be supported by SimpleComic.

I'll have to test to make sure, though.

**Comment by nickv2002** [comment]
I just tested with a mixture of HEIC and JPEG images and it all showed up in the correct order.

**Comment by nickv2002** [comment]
(This is assuming you're using a recent version of macOS that supports HEIC natively. I think it was added to High Sierra but it definitely works for me on Catalina. If you're on an older version, it won't work an it's not really worth adding custom support for that.)

**Comment by sygao** [comment]
One minor caveat: HEIC isn't explicitly listed as a document type yet, so Finder won't allow you to open HEIC files via the right-click menu (Open With and etc). Can that be added that in the next App Store build?

**Comment by nickv2002** [comment]
That should be no problem @sygao 
Thanks for the suggestion

**Comment by nickv2002** [comment]
Fixed in https://github.com/MaddTheSane/Simple-Comic/pull/31 which is [live on the app store](https://apps.apple.com/us/app/simple-comic/id1497435571?mt=12) (version 1.8.6)
