### ISSUE TITLE
Future Plan

### ISSUE THREAD

**Issue by nickv2002** [MaddTheSane/Simple-Comic#3]
For the initial plan I'd just like to get a build working on Catalina so that we can get it fully signed and notarized by Apple (so people can open it without having to Control-Click Open).

Then after that perhaps we can get a build up on the Mac App Store for easy redistribution.

Third, we can move forward with bug fixes and feature requests, along with translations and a better web presence.

How's that sound to you @MaddTheSane?

**Comment by MaddTheSane** [comment]
Sounds good to me.

I'm currently reading a book about CoreData, as I don't feel like my versioning of the data model was done correctly.

Another long-term goal for me is to make loading of images to happen asynchronously, thus freeing up the app when a large comic archive (or one over the network) is used. This will probably be after a new release, though.

**Comment by ronaldsuwandi** [comment]
Will there be any announcement when the App store version is up?

**Comment by nickv2002** [comment]
Mac App store version is up here:
https://apps.apple.com/us/app/simple-comic/id1497435571
(I hadn't publicized it much yet because I was kicking the tires but so far it's working well, please let us know here if you find any issues.)

**Comment by johnatpackawhallop** [comment]
Thanks so much for making this work on Catalina and putting it in the Mac App Store.

Question. The icons for .cbr and .cbz files on macOS used to be "flat" such that you could see the entire cover. Now they have the curled dog-ear upper right corner document-style icon. Does anyone know why this happened and is there a way to fix it or change it? Thanks!

**Comment by peirantan** [comment]
> Mac App store version is up here:
> https://apps.apple.com/us/app/simple-comic/id1497435571
> (I hadn't publicized it much yet because I was kicking the tires but so far it's working well, please let us know here if you find any issues.)

Just got it from the MAS. You sir are a real hero.

**Comment by Envo** [comment]
Maybe it's time to support heic files inside the archive. We could save a lot of disk space.

**Comment by nickv2002** [comment]
Closing this issue thread as it's several years old.
