### ISSUE TITLE
Disable error "beep" sound when pressing an unbound key

### ISSUE THREAD

**Issue by doroshenko** [MaddTheSane/Simple-Comic#36]
Hey! 

Currently when you press a key that is not associated with any of the Simple Comic hotkeys, the app produces a system error "beep" sound. I personally find this quite annoying.

What do you guys think about it? If there's an interest in changing this behavior, I can open a PR. It should be a simple one-line fix.

**Comment by blmatthews** [comment]
A user performing an action and getting *zero* feedback is terrible UX. If I hit a key, and nothing happens, I'm left wondering is what I'm trying to do just slow (and there's no progress indicator), is that function broken, is the app hung, is my computer hung... The beep tells me definitively and immediately I hit a wrong key, so I can take corrective action.

**Comment by doroshenko** [comment]
After investigating a bit more, it turns out that Simple Comic's behavior in this case is consistent with most of the native macOS apps, and the beep volume for any application could be controlled through the "Alert volume" slider in system sound settings. As such, I'm closing this issue.
