### ISSUE TITLE
Can't set page as file icon

### ISSUE THREAD

**Issue by ppzjd** [MaddTheSane/Simple-Comic#39]
Running v1.8.8 on 10.15.7, and I am unable to set a page as the file icon for the Finder.  I'm unsure if this is a Mac OS problem or not.  Tried this with both .cbr and .cbz files, but no dice.  Thanks so much in advance for any insight or assistance!

**Comment by nickv2002** [comment]
What icon size are you using in the Finder?
See related issue/explanation here https://github.com/MaddTheSane/Simple-Comic/issues/17

**Comment by ppzjd** [comment]
Actually, after I restarted my iMac, Nick, newly-downloaded .cbr files already come up with the icon preview, so this was all that was needed for me for Quick View!  FYI, though, in case anyone else is reading this thread, I have my icon size set at 48 x 48, so this would be a good reference size for anyone -- not sure what the minimum size would be otherwise.  Thanks so, so much for your quick response!
