### ISSUE TITLE
Current version crashes when opening files

### ISSUE THREAD

**Issue by thebearmayor** [MaddTheSane/Simple-Comic#43]
Application crashes when opening any file. This is a new issue with the current version from App Store. OS is Mojave 10.14.6.

Crash log:
[Simple Comic_2020-11-28-213005_bpeterson.crash.txt](https://github.com/MaddTheSane/Simple-Comic/files/5611600/Simple.Comic_2020-11-28-213005_bpeterson.crash.txt)

I'm happy to help with troubleshooting in any way, including testing patches.

**Comment by MaddTheSane** [comment]
Can confirm. I think I found a fix.
This issue doesn't happen on later OS releases.

**Comment by thebearmayor** [comment]
Thanks, works for me.
