### ISSUE TITLE
Black text in the About window looks bad in dark mode

### ISSUE THREAD

**Issue by euf** [MaddTheSane/Simple-Comic#52]
As title says:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/11754264/115142537-f8f8a180-a04a-11eb-9ec3-12e57f45c17c.png">
(App Store version)

**Comment by MaddTheSane** [comment]
What OS are you using?

**Comment by DavidPhillipOster** [comment]
I think you can close this issue

**Comment by MaddTheSane** [comment]
Agreed. Closed by #98.
