### ISSUE TITLE
Cannot open file error in Big Sur

### ISSUE THREAD

**Issue by roosterboy** [MaddTheSane/Simple-Comic#54]
So I finally upgraded to Big Sur last weekend. Ever since, I get the attached error dialog whenever I open a CBR or CBZ file. Fortunately, SimpleComic still opens and works properly after dismissing the error.

<img width="372" alt="Screen Shot 2021-05-15 at 10 01 17" src="https://user-images.githubusercontent.com/5996293/118372083-881ea980-b564-11eb-8ab3-27f727169708.png">

**Comment by nickv2002** [comment]
That's an odd one I haven't seen before. Lots of people using Big Sur so I doubt it's specifically related to that OS version.

Perhaps you can delete the app and any _Application Support_ files and re-download from the Mac App Store to see if that fixes things?

**Comment by roosterboy** [comment]
That didn't fix things, unfortunately.

I mean, it's a minor annoyance right now since the files actually do open and, as far as I can tell, there is no degradation of functionality.

**Comment by roosterboy** [comment]
And now, all of a sudden, I no longer get that message when I open a CBR or CBZ file. As of yesterday, I was still getting it. No recent system updates or anything else I can think of that might explain it. Weird.

The only thing system related I did in the last day or so was delete the container folder contents for Books.app and then restart, because Books couldn't access my library since upgrading to Big Sur. But SimpleComic wouldn't be accessing any of that, right?
