### ISSUE TITLE
Monterey TestFlight Beta

### ISSUE THREAD

**Issue by nickv2002** [MaddTheSane/Simple-Comic#61]
If you have Monterey you can join the [TestFlight beta of the new App store build here](https://testflight.apple.com/join/oHcg1JAt). Please give it a shot and LMK if there are any issues. If things look good I'll release this as 1.9.2. Build is based on https://github.com/MaddTheSane/Simple-Comic/commit/bf801a7071c33b902fbb6ef77a93be1f8358d19b

**Comment by johannkoenig** [comment]
I had to change the link (https->itms-beta): [itms-beta://testflight.apple.com/join/oHcg1JAt](itms-beta://testflight.apple.com/join/oHcg1JAt) but now it's installed and working. No issues so far.

**Comment by sygao** [comment]
Installed it on the M1 Mac Mini and read a few volumes, didn't run into any issues either.

**Comment by nickv2002** [comment]
Thanks for the feedback. I pushed this 1.9.2 release out to the general App Store audience and made a signed release here https://github.com/MaddTheSane/Simple-Comic/releases/tag/App-Store-1.9.2
