### ISSUE TITLE
Since 1.9.2 update, upon opening, app doesn't keep newly-opened books in memory

### ISSUE THREAD

**Issue by ppzjd** [MaddTheSane/Simple-Comic#62]
Upon opening the app, newly updated to 1.9.2, the first book opened is one I was reading prior to the update, even the exact same page!  Newly-opened books are still mentioned in both the "Open Recent" menu bar and in the Dock, but that older one is in the Dock as well.  This keeps happening no matter how many times I quit and reopen, whether I move the older file to a different folder, or even rename it.  Just wanted to bring this to your attention...thanks!

**Comment by nickv2002** [comment]
Thanks for the report @ppzjd - not sure I fully understand the problem though. What you described sounds like things working correctly. Perhaps you could clarify the specific problem with a screenshot?

**Comment by ppzjd** [comment]
Hi, thanks for promptly responding, most appreciated!  This actually isn't the behavior that the app used to perform, since once I closed a comic, it would not ever reopen.  Also, newly opened books in the app do not appear after I quit and restart the program, just that one older book.  I have taken a screenshot, since I don't think I am quite explaining it properly.  This would be what I see when I first open the app.  The two books in the "Open Recent" menu do not appear when first opening the program, just this same book pictured here opening all the time.  Let me know if this helps, and then I can explain more.  Thanks in advance
<img width="991" alt="Screen Shot 2021-12-10 at 1 39 02 PM" src="https://user-images.githubusercontent.com/72168357/145631876-3cf3c8d6-ae2d-4b8f-a469-eb6fae46d099.png">
!

**Comment by nickv2002** [comment]
See https://github.com/MaddTheSane/Simple-Comic/commit/e480be770a986b2d32dc0213be499481d13714fd which modified the window restore behavior. Window restoration on launch should now follow your system settings. Please check your system settings to adjust this behavior. Monterey and Ventura screenshots below:
<img width="400" alt="Ventura Settings" src="https://user-images.githubusercontent.com/704392/216211150-53642505-09e5-4d7b-aba9-78acfca202c8.png"><img width="400" alt="Monterey Settings" src="https://user-images.githubusercontent.com/704392/145659908-f8823231-b339-4f86-a72d-bdc259c23f82.png">

Note this setting only affects when you open Simple Comic itself. Opening a comic file from the Finder will always open a new window of that comic (potentially a second if you already have it open). This is all default macOS behavior.

**Comment by ppzjd** [comment]
nickv, that solved my issue PERFECTLY!  Fantastic support, for sure.  Thanks so much!
