### ISSUE TITLE
Opened Files Are Not Reopened After Restarting

### ISSUE THREAD

**Issue by PsyPryss** [MaddTheSane/Simple-Comic#63]
Previously opened files are not reopened after quitting and restarting app like in 1.9.1. Moreover the open button and other UI are gold coloured instead of the system's blue. Not sure if related.

**Comment by nickv2002** [comment]
This was an intended change. The app now follows the system setting. See https://github.com/MaddTheSane/Simple-Comic/issues/62#issuecomment-991409135 for more details on how to change it.
