### ISSUE TITLE
enhancement: Live Text in Simple Comic

### ISSUE THREAD

**Issue by DavidPhillipOster** [MaddTheSane/Simple-Comic#69]
I'm interested in weak-linking Apple's Vision framework into SimpleComic. The `Vision.framework` provides OCR services. so: 
* You can use the mouse to sweep out and select the text and copy it to the clipboard like you can by opening a single `.jpg` in **Preview** on an Apple Silicon Mac. (Apple's Live Text feature.) 
* The text in a cbr/cbz can be indexed by a Spotlight plugin, like SimpleComic's QuickLook plugin.
* Stretch goal: Live translation: example: Fade out the original Japanese text and instead show machine-translated English: (by adding a menu letting Simple Comic know what language to OCR the text, and using an API like Google's to do the actual translation) 

So far, I've built and run Simple Comic from source and added the weak-linked Vision Framework. I've written a working model of the first bullet point - now to integrate that into Simple Comic's mouse and page handling.

**Comment by nickv2002** [comment]
Great idea!

I've been impressed with the Preview live text support so it would be neat to see it in Simple Comic as long as it was unobtrusive.

I would say that your stretch goal of translation might be beyond the scope of what we want to include. I have worries about adding bulky 3rd-party translation APIs, APIs that might contribute to tracking, and/or online service requirements.

**Comment by DavidPhillipOster** [comment]
Also:
* The OCRed text can easily be connected to the built-in text-to-speech engine, which would let anyone who can't read still experience a graphic novel by just pointing at a word balloon.

Here's what I've got so far: https://github.com/DavidPhillipOster/MockSimpleComic a sample app that shows the power of the Vision framework. It OCRs a sample page, displaying where on the page it found the text and dumping the text to the console. The code is short, and lives in [OCRedTextView.{h,m}](https://github.com/DavidPhillipOster/MockSimpleComic/blob/main/MockSimpleComic/OCRedTextView.m), a transparent overlay NSView on top of the page image.

I'm happy to reformat it to match SimpleComic's coding standards, and I'll sign any documents necessary to be a collaborator.

**Comment by MaddTheSane** [comment]
I have no issue with adding OCR support.
As for translation: Apple Silicon Macs have a translation option available. It doesn't live-translate, but you select text, right-click (or control-click), and it's the second menu option. It pops up a pop-up view, allowing you to select which language the source is, and which language to translate to. It'll even show other possible meanings if it isn't sure which you mean.
Pull requests are always appreciated.

**Comment by DavidPhillipOster** [comment]
Thanks!  When I get as far as a pull request, I'll attempt to make it as unobtrusive as it is in Apple's **Preview** when you have a .jpg open.
I had a bug in the source language selection part of MockSimpleComic, now fixed. It now correctly fetches the list of Monterey source OCR languages: en-US, fr-FR, it-IT, de-DE, es-ES, pt-BR, zh-Hans, zh-Hant

**Comment by DavidPhillipOster** [comment]
I've got https://github.com/DavidPhillipOster/MockSimpleComic working well enough. Next I'll start integrating that code into a branch of Simple Comics - I'm new to contributing to projects like this: how should I do pull requests so I don't just dump a load of code on you for you to review?

**Comment by DavidPhillipOster** [comment]
I've got this working in the easy case in my fork in the OCR branch: https://github.com/DavidPhillipOster/Simple-Comic/tree/OCR

git commit b3e4cb6, is where I changed the bundle ID and TEAM to me, so you can pull that commit out to keep the original bundle ID and signature.

where the easy case is defined as one simple page, a jpg, png, or non-animated gif. Rotations and scaling work.

• cursor changes to iBeam when over selectable text.
• click-and-drag to select live text. Selectable words within the dragged out rectangle are selected.
• Copy, Select All, and Speak, on the Edit menu work.
• Control-click on selected text for a contextual menu.
• Command click to add a new selection rectangle to the existing selection.

**TODO:**
• two page spreads
• a Find dialog modeled after the one on Apple's Terminal
• a Spotlight extension so you can use Spotlight to find all books with a specific phrase, then search within the book.
• Control over the default OCR language. For now, you get the system default (English in my case.)
• Update the README and the Help book. 
• Localization of the new menu items.

**HELP NEEDED:**

When I try to run this on my old macOS 10.13 laptop, it fails initializing Core Data, complaining that two ImageGroups can't be reconciled. Without Core Data I can't open any files. None of this is my code. I'd like help getting past this so I can verify that my changes did not break the app, when run on old machines.

**Comment by DavidPhillipOster** [comment]
See: https://github.com/MaddTheSane/Simple-Comic/pull/71

**Comment by DavidPhillipOster** [comment]
Thank you!  I designed OCRTracker so if **Simple Comic** ever decides to show more than two images in a TSSTPageView then OCRTracker's datums array can be initialized with more elements and it all should just work.
