### ISSUE TITLE
QuickLook doesn't work

### ISSUE THREAD

**Issue by Ackthbpt** [MaddTheSane/Simple-Comic#7]
When running the `Simple Comic 2020-01-12 12-05-43` version on Catalina (10.15.2) QuickLook doesn't work.

**Comment by manuelgrabowski** [comment]
It works fine for me, I'm also on 10.15.2. You're talking about the version from #5?

**Comment by Ackthbpt** [comment]
I am, yes.  Is there some way to "purge" or "reset" QuickLook?  In years past, I may have added custom QL plugins and maybe one of those is interfering?

**Comment by Ackthbpt** [comment]
When I try to generate from the command line using `qlmanage -p SomeComic.cbr`, I get this:
```
2020-01-18 19:13:18.053 qlmanage[47029:16375549] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9603, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-01-18 19:13:18.248 qlmanage[47029:16375549] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb11b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

I've run `qlmanage -r` and `qlmanage -r cache` multiple times - both with and without `sudo` - with no change.

**Comment by manuelgrabowski** [comment]
What do you have in your `~/Library/QuickLook` and `/Library/QuickLook` directories? Any leftovers in there that might interfere?

Can you post the output of these two commands (assuming you put it in your Applications directory of course):
`xattr /Applications/Simple\ Comic.app`
and
`xattr /Applications/Simple\ Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator`

(The output would ideally be empty.)

**Comment by Ackthbpt** [comment]
Sure thing.  Both of the `xattr` commands return `com.apple.quarantine` which just doesn't seem like a *good* thing.

The only thing I have in `~/Library/QuickLook` is `QLAddict.qlgenerator` which is a QL plugin fot `.srt` files, and `/Library/QuickLook` has both `iWork.qlgenerator` and `Video.qlgenerator` in it.

**Comment by manuelgrabowski** [comment]
Ah, there we go, that's the reason then. Good news and bad news:

Good: You can easily fix it by running the `xattr` command again, but with the parameters set to remove the attribute: `xattr -r -d com.apple.quarantine path`
Afterwards QuickLook should work, though I'm not sure if you need to run it just on the QuickLook plugin inside the app, just on the app, or on both.

Bad: I have no idea why in your case the attribute was present and it was not in my case.
That attribute is set by macOS on downloaded applications, and it's the reason for that warning popup when you first open such applications. However, QuickLook plugins are not able to trigger that popup and thus just don't run when they have the attribute.

I'm not sure if it is macOS or just Safari that is setting the attribute, so maybe downloading the application via e.g. Chrome would have a different result. But I used Safari, and I didn't have the attribute set. You did run the app once before trying QuickLook?
Another difference I could think of: I'm using BetterZip instead of the included Archive Utility. Maybe upon extracting the downloaded ZIP file, BetterZip drops the attribute, while Archive Utility preserves it?

**Comment by Ackthbpt** [comment]
Alas, this did not fix my issue.  I removed the `xattr` from the original ZIP file, then installed it, opened it, and checked the two `xattr`s that you asked about earlier and the `com.apple.quarantine` is indeed gone, but QL still doesn't work.

**Comment by manuelgrabowski** [comment]
Huh, that's odd. Same error message as in your previous post?

What are your settings in here:
![image](https://user-images.githubusercontent.com/13483728/72870772-63585000-3ce9-11ea-8d20-502045e4e420.png)

**Comment by manuelgrabowski** [comment]
Here is a list of other things to try, maybe one of those steps will work for you: https://michaelbach.de/2019/11/14/Markdown-quicklook-in-Catalina.html

Still so weird that I had to do none of that. Is your Catalina a clean install or did you upgrade from a previous version?

**Comment by erutan** [comment]
Chiming in that 3 sources of .cbr and .cbz files worked on my side from the new notarized app Version 1.8.3 (255) (for whatever that's worth).

**Comment by Ackthbpt** [comment]
@manuelgrabowski My settings look identical to that screen (with the addition of some Apple Watch stuff).  And none of the suggestions in that link worked.  My Catalina is an upgrade, not a clean install.

I don't know if any of this helps, but if I run `qlmananage -m | grep cbr` then I get:
```
  com.macitbetter.cbr-archive -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
  com.milke.cbr-archive -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
  cx.c3.cbr-archive -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
  public.cbr-archive -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
  public.archive.cbr -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
  com.bitcartel.comicbooklover.cbr -> /Applications/Simple Comic.app/Contents/Library/QuickLook/QuickComic.qlgenerator (12)
```
So it looks like all of the QL associations are there.  And if I try doing `qlmanage -p [PATH TO CBR FILE]` then I (still) get:
```
2020-01-22 20:11:42.692 qlmanage[5595:414252] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6a03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-01-22 20:11:42.750 qlmanage[5595:414252] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x1461f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```
Those files do not exist on my system.  I'm at a loss of what to do here, and any suggestions are definitely appreciated, either to fix it or diagnose it further.

**Comment by Ackthbpt** [comment]
Also, I was going to try building it for myself, but cloning the git repo and following the directions doesn't work.  I get a `error: Build input file cannot be found: '/Users/Paul/Downloads/Simple-Comic/Vendor/ios-osx-webp-decoder/libwebp/src/utils/bit_writer_utils.c' (in target 'WebPMac' from project 'libwebp')` when I try.  When I check, the `libwebp` directory is completely empty.  If this isn't a rabbit hole I should go down, feel free to say so.  =)

**Comment by MaddTheSane** [comment]
> Also, I was going to try building it for myself, but cloning the git repo and following the directions doesn't work. I get a `error: Build input file cannot be found: '/Users/Paul/Downloads/Simple-Comic/Vendor/ios-osx-webp-decoder/libwebp/src/utils/bit_writer_utils.c' (in target 'WebPMac' from project 'libwebp')` when I try.

`git submodule update --init --recursive`. The `--recursive` is the crucial part.

**Comment by Ackthbpt** [comment]
Gotcha.  Could I recommend that that be added to the README?  I was able to build once I did that.

Unfortunately, the issue persists.

UPDATE - no it doesn't.  Once I closed Xcode, the QL preview started working.  I'm very perplexed, but at least it's functional now.

**Comment by nickv2002** [comment]
Closing for now; please re-open if you experience more issue that you can document.
Thanks for the good back and forth.
