### ISSUE TITLE
Background Color Preference not saved

### ISSUE THREAD

**Issue by DizzieDawgie** [MaddTheSane/Simple-Comic#8]
The Simple-Comic preferences window has four settings: a background color picker and three other check boxes. When checking/unchecking the three boxes, the settings are preserved after closing and re-opening the application (as expected), but the background color always resets to white (NOT as expected). After changing the color to black I'd expect that color preference to be saved like the other settings but it is not.

I'm using the latest files from Github as of the commits on Jan 22, 2020, built with Xcode Version 11.3.1 (11C504) on a Mac mini (2018), macOS Catalina Version 10.15.2.

**Comment by MaddTheSane** [comment]
Can confirm. Investigating.
