### ISSUE TITLE
iPad/iOS

### ISSUE THREAD

**Issue by yosamsimiti** [MaddTheSane/Simple-Comic#86]
Any plans to make a port to iPads and iPhones?

**Comment by nickv2002** [comment]
No, there's too much work just to handle file management on iOS.
There are several other apps that do this well already, I personally use & like [YACReader](https://apps.apple.com/app/id635717885).

**Comment by yosamsimiti** [comment]
YACReader kinda sucks, least compared to simple comic what with the ocr stuff…which is like gold if it were fully realized and actualized…perhaps in another alternate comic book universe then….sigh

**Comment by nickv2002** [comment]
Glad you're enjoying the OCR features as those were a great feature added by @DavidPhillipOster

YACReader does have some similar OCR features (eg selecting copying text in speech bubbles), not sure if you found them already and were dissatisfied or didn't know they were there.

I should clarify that I'm not strictly against an iOS version of Simple Comic, but it would not be a quick and easy thing to port. That said, it's open source and PRs are welcome. If someone gets something working I'm happy to help publish it.
