### ISSUE TITLE
Closing comic while full-screen crashes app

### ISSUE THREAD

**Issue by DizzieDawgie** [MaddTheSane/Simple-Comic#9]
Steps to reproduce:
- Drag a folder of images (or a single image) to the Simple-Comic icon in the Dock. App opens and displays first image.
- Click green expand button in top-left of window to maximize the app. App goes full screen.
- Type Cmd-W to close the window.

At this point I'd expect the app to close the opened full-screen comic. Instead it quits with an OS popup that reads "Simple Comic quit unexpectedly." with Ignore/Report/Reopen buttons.

**Comment by MaddTheSane** [comment]
Found out a couple of places that cause this error. Fix incoming.
