### ISSUE TITLE
"Persistent store migration failed, missing mapping model."

### ISSUE THREAD

**Issue by nihilrien** [MaddTheSane/Simple-Comic#93]
I just upgraded to v1.9.5 last night (had been using something in the 1.7 range) and now, whenever I close the application and reopen, none of the comics I had open at the time of shutdown appear and, instead, I get an error message saying "Persistent store migration failed, missing mapping model."

**Comment by nickv2002** [comment]
Can you try removing your prefs and containers for SimpleComic?

```
rm -ivr ~/Library/*/*SimpleComic*
```

**Comment by nihilrien** [comment]
Is that something to enter in Terminal?  If so, I just did and got the response "examine files in directory /Users/ryanfrank/Library/Containers/com.ToWatchList.SimpleComic? "

The error continued.

**Comment by nickv2002** [comment]
Please delete or trash this directory: `/Users/ryanfrank/Library/Containers/com.towatchlist.SimpleComic` while SimpleComic is closed and then try to start it again.

**Comment by nihilrien** [comment]
Thank you, but no luck finding that.  /Users/ryanfrank doesn't contain a folder named "Library."  I did find one marked "Library" on the hard drive, but it doesn't contain a folder named "Containers" and I searched the hard drive and couldn't find any file named com.towatchlist.SimpleComic or towatchlist.SimpleComic.

**Comment by nihilrien** [comment]
(And yes, I see that's what Terminal talked about and so it must exist, but I have no idea how to find it to delete it.)

**Comment by nickv2002** [comment]
[Here's how to get to `~/Library` in the Finder](https://www.macrumors.com/how-to/reveal-library-folder-in-macos/)

**Comment by nihilrien** [comment]
Thank you!  Found it and deleted it, so I'm not getting the original error message anymore, but comics that were open prior to quitting still do not appear when the application reopens.

**Comment by nickv2002** [comment]
👍 - for info about state restoration see https://github.com/MaddTheSane/Simple-Comic/issues/62#issuecomment-991409135
